-- SailCircle Supabase backend
-- Run this in Supabase Dashboard > SQL Editor > New query

create table if not exists public.sailors (
  id bigint generated by default as identity primary key,
  name text not null,
  boat text not null default 'No boat',
  status text not null default 'Open to meet',
  location text not null,
  trip text,
  date text,
  skill text,
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  title text not null,
  route text not null,
  spots integer not null default 1 check (spots >= 0),
  date text not null,
  level text not null,
  host text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  replies integer not null default 0,
  tag text not null,
  author text not null,
  created_at timestamp with time zone default now()
);

alter table public.sailors enable row level security;
alter table public.trips enable row level security;
alter table public.forum_posts enable row level security;

-- Public read policies for an MVP.
-- For a serious product, add authentication and stricter policies.
drop policy if exists "Allow public read sailors" on public.sailors;
create policy "Allow public read sailors"
on public.sailors for select
using (true);

drop policy if exists "Allow public read trips" on public.trips;
create policy "Allow public read trips"
on public.trips for select
using (true);

drop policy if exists "Allow public read forum posts" on public.forum_posts;
create policy "Allow public read forum posts"
on public.forum_posts for select
using (true);

drop policy if exists "Allow public insert trips" on public.trips;
create policy "Allow public insert trips"
on public.trips for insert
with check (true);

insert into public.sailors (name, boat, status, location, trip, date, skill, latitude, longitude) values
('Marta & João', 'Beneteau 36', 'Looking for crew', 'Cascais Marina', 'Cascais → Lagos', 'May 12', 'Coastal cruising', 38.6979, -9.4215),
('Sofie', 'X-Yachts 34', 'Open to meet', 'Copenhagen', 'Øresund weekend sail', 'May 18', 'Racing', 55.6761, 12.5683),
('Andreas', 'Hallberg-Rassy 42', 'Planning passage', 'Kiel', 'Kiel → Bornholm', 'June 2', 'Offshore', 54.3233, 10.1228),
('Lea', 'No boat', 'Wants to join', 'Mallorca', 'Balearic Islands', 'Flexible', 'Beginner', 39.5696, 2.6502)
on conflict do nothing;

insert into public.trips (title, route, spots, date, level, host) values
('Weekend sail around Øresund', 'Copenhagen → Helsingør → Ven', 2, '18–19 May', 'Beginner friendly', 'Sofie'),
('Portugal coastal cruise', 'Cascais → Sines → Lagos', 1, '12–17 May', 'Intermediate', 'Marta & João'),
('Baltic mini passage', 'Kiel → Bornholm', 3, '2–6 June', 'Offshore experience', 'Andreas')
on conflict do nothing;

insert into public.forum_posts (title, replies, tag, author) values
('Best apps for weather routing in the Baltic?', 18, 'Navigation', 'Sofie'),
('How do you split costs fairly with guest crew?', 34, 'Crew', 'Marta'),
('First overnight passage — what should I prepare?', 12, 'Beginner', 'Lea')
on conflict do nothing;
