-- SailCircle Complete MVP Schema
-- Run this whole file in Supabase SQL Editor.
-- It replaces/extends the old prototype schema.
-- Safe for a development project. If you already have important data, export it first.

create extension if not exists "pgcrypto";

-- Existing tables are extended, not dropped.
create table if not exists public.sailors (
  id bigint generated by default as identity primary key,
  name text not null,
  boat text not null default 'No boat',
  status text not null default 'Open to meet',
  location text not null,
  trip text,
  date text,
  skill text,
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  title text not null,
  route text not null,
  spots integer not null default 1 check (spots >= 0),
  date text not null,
  level text not null,
  host text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  replies integer not null default 0,
  tag text not null,
  author text not null,
  created_at timestamp with time zone default now()
);

alter table public.trips
add column if not exists description text default 'More details to be confirmed by the host.',
add column if not exists meeting_point text default 'To be confirmed',
add column if not exists cost_notes text default 'Costs to be agreed between skipper and crew.',
add column if not exists requirements text default 'To be confirmed',
add column if not exists city text default 'Copenhagen',
add column if not exists country text default 'Denmark',
add column if not exists region text default 'Europe',
add column if not exists latitude double precision default 55.6761,
add column if not exists longitude double precision default 12.5683,
add column if not exists is_location_approximate boolean default true,
add column if not exists owner_id uuid references auth.users(id) on delete set null,
add column if not exists updated_at timestamp with time zone default now();

alter table public.forum_posts
add column if not exists body text default '',
add column if not exists owner_id uuid references auth.users(id) on delete set null,
add column if not exists updated_at timestamp with time zone default now();

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  home_port text,
  region text default 'Europe',
  bio text,
  skill_level text default 'Beginner',
  verified boolean default false,
  show_approx_location boolean default true,
  latitude double precision,
  longitude double precision,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.boats (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  name text not null,
  model text,
  length text,
  home_port text,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.trip_requests (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade,
  requester_id uuid references auth.users(id) on delete cascade,
  owner_id uuid references auth.users(id) on delete set null,
  name text not null,
  message text not null,
  status text default 'pending',
  created_at timestamp with time zone default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete cascade,
  receiver_id uuid references auth.users(id) on delete cascade,
  body text not null,
  read_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

create table if not exists public.forum_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.forum_posts(id) on delete cascade,
  author_id uuid references auth.users(id) on delete set null,
  author text not null,
  comment text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade,
  reviewer_id uuid references auth.users(id) on delete cascade,
  reviewed_user_id uuid references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamp with time zone default now()
);

create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  region text default 'Europe',
  note text,
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table public.sailors enable row level security;
alter table public.trips enable row level security;
alter table public.forum_posts enable row level security;
alter table public.profiles enable row level security;
alter table public.boats enable row level security;
alter table public.trip_requests enable row level security;
alter table public.messages enable row level security;
alter table public.forum_comments enable row level security;
alter table public.reviews enable row level security;
alter table public.availability enable row level security;

-- Public reads for discovery
drop policy if exists "Public read sailors" on public.sailors;
create policy "Public read sailors" on public.sailors for select using (true);

drop policy if exists "Public read trips" on public.trips;
create policy "Public read trips" on public.trips for select using (true);

drop policy if exists "Public read forum posts" on public.forum_posts;
create policy "Public read forum posts" on public.forum_posts for select using (true);

drop policy if exists "Public read forum comments" on public.forum_comments;
create policy "Public read forum comments" on public.forum_comments for select using (true);

drop policy if exists "Public read profiles" on public.profiles;
create policy "Public read profiles" on public.profiles for select using (true);

drop policy if exists "Public read boats" on public.boats;
create policy "Public read boats" on public.boats for select using (true);

drop policy if exists "Public read reviews" on public.reviews;
create policy "Public read reviews" on public.reviews for select using (true);

drop policy if exists "Public read availability" on public.availability;
create policy "Public read availability" on public.availability for select using (true);

-- Authenticated creation/update
drop policy if exists "Users manage own profile" on public.profiles;
create policy "Users manage own profile" on public.profiles
for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Users manage own boats" on public.boats;
create policy "Users manage own boats" on public.boats
for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Authenticated create trips" on public.trips;
create policy "Authenticated create trips" on public.trips
for insert to authenticated with check (auth.uid() = owner_id);

drop policy if exists "Owners update own trips" on public.trips;
create policy "Owners update own trips" on public.trips
for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Authenticated create forum posts" on public.forum_posts;
create policy "Authenticated create forum posts" on public.forum_posts
for insert to authenticated with check (auth.uid() = owner_id);

drop policy if exists "Owners update own forum posts" on public.forum_posts;
create policy "Owners update own forum posts" on public.forum_posts
for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Authenticated create comments" on public.forum_comments;
create policy "Authenticated create comments" on public.forum_comments
for insert to authenticated with check (auth.uid() = author_id);

drop policy if exists "Authenticated create trip requests" on public.trip_requests;
create policy "Authenticated create trip requests" on public.trip_requests
for insert to authenticated with check (auth.uid() = requester_id);

drop policy if exists "Users read related trip requests" on public.trip_requests;
create policy "Users read related trip requests" on public.trip_requests
for select to authenticated using (auth.uid() = requester_id or auth.uid() = owner_id);

drop policy if exists "Users update owned trip requests" on public.trip_requests;
create policy "Users update owned trip requests" on public.trip_requests
for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Users read own messages" on public.messages;
create policy "Users read own messages" on public.messages
for select to authenticated using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "Users send messages" on public.messages;
create policy "Users send messages" on public.messages
for insert to authenticated with check (auth.uid() = sender_id);

drop policy if exists "Authenticated create reviews" on public.reviews;
create policy "Authenticated create reviews" on public.reviews
for insert to authenticated with check (auth.uid() = reviewer_id);

drop policy if exists "Users manage own availability" on public.availability;
create policy "Users manage own availability" on public.availability
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Sample seed data. Duplicate rows may appear if run many times; acceptable for development.
insert into public.sailors (name, boat, status, location, trip, date, skill, latitude, longitude) values
('Marta & João', 'Beneteau 36', 'Looking for crew', 'Cascais Marina', 'Cascais → Lagos', 'May 12', 'Coastal cruising', 38.6979, -9.4215),
('Sofie', 'X-Yachts 34', 'Open to meet', 'Copenhagen', 'Øresund weekend sail', 'May 18', 'Racing', 55.6761, 12.5683),
('Andreas', 'Hallberg-Rassy 42', 'Planning passage', 'Kiel', 'Kiel → Bornholm', 'June 2', 'Offshore', 54.3233, 10.1228),
('Lea', 'No boat', 'Wants to join', 'Mallorca', 'Balearic Islands', 'Flexible', 'Beginner', 39.5696, 2.6502);

insert into public.trips (title, route, spots, date, level, host, description, meeting_point, cost_notes, requirements, city, country, region, latitude, longitude, is_location_approximate) values
('Weekend sail around Øresund', 'Copenhagen → Helsingør → Ven', 2, '18–19 May', 'Beginner friendly', 'Sofie', 'A relaxed weekend trip around Øresund for sailors who want to meet others.', 'Copenhagen Marina', 'Shared food and marina costs.', 'Beginner friendly.', 'Copenhagen', 'Denmark', 'Europe', 55.6761, 12.5683, true),
('Portugal coastal cruise', 'Cascais → Sines → Lagos', 1, '12–17 May', 'Intermediate', 'Marta & João', 'A coastal cruise down the Portuguese coast.', 'Cascais Marina', 'Shared fuel, food, and marina costs.', 'Some sailing experience preferred.', 'Cascais', 'Portugal', 'Europe', 38.6979, -9.4215, true),
('Baltic mini passage', 'Kiel → Bornholm', 3, '2–6 June', 'Offshore experience', 'Andreas', 'A longer Baltic passage for people interested in offshore sailing.', 'Kiel harbour', 'Shared expenses agreed before departure.', 'Comfortable with overnight sailing.', 'Kiel', 'Germany', 'Europe', 54.3233, 10.1228, true);

insert into public.forum_posts (title, replies, tag, author, body) values
('Best apps for weather routing in the Baltic?', 18, 'Navigation', 'Sofie', 'Looking for charting and weather tools for a summer Baltic trip.'),
('How do you split costs fairly with guest crew?', 34, 'Crew', 'Marta', 'Curious about what is normal for food, marina, and fuel sharing.'),
('First overnight passage — what should I prepare?', 12, 'Beginner', 'Lea', 'Planning my first overnight trip and want a checklist.');
